### PR TITLE
sidharth-t-tamu-madlibs

### PR DESCRIPTION
**Pull request by sidharth-t-tamu**
I made the changes with the square brackets

### CODE REVIEW

**Review by SaiHarsha-P — CHANGES_REQUESTED** [review]
Please remove the square brackets and keep just the words in the story.txt file
Ex. Not [lumpy], but just lumpy

**Review by JanvitaReddy11 — COMMENTED** [review]
'Gold', 'running' and 'away' all these words should be in lowercase

**Review by SaiHarsha-P — APPROVED** [review]
Looks good.

**Review by JanvitaReddy11 — APPROVED** [review]
The concept of gold bed is unique

**Review by JanvitaReddy11 — COMMENTED** [review]
It is good

**Pull request merged**
